[package]
name = "lldb-gui"
version = "0.1.0"
edition = "2021"

[build-dependencies]
autocxx-build = "0.26.0"
miette = { version = "5", features = ["fancy"] }

[dependencies]
eframe = "0.27.0"
rfd = "0.14.1"
autocxx = "0.26.0"
cxx = "1.0"
