[package]
name = "lldbui"
version = "0.1.0"
edition = "2021"
authors = ["Dennis Schön <mail@dennis-schoen.de>"]

[dependencies]
egui = "0.27.0"
eframe = "0.27.0"
lldb = "0.0.11"
clap = { version = "4.5.4", features = ["derive"] }
